<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>SimpleKioskOS</Company>
    <Product>SimpleKioskOS</Product>
    <AssemblyCopyright>Copyright SimpleKioskOS</AssemblyCopyright>
  </PropertyGroup>
</Project>
