<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\OTM.Shared\OTM.Shared.csproj" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Otm.Kiosk.Service</RootNamespace>
  </PropertyGroup>
</Project>
