<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Resource Include="..\OTM.KioskShell\Assets\simplekioskos.ico" Link="Assets\simplekioskos.ico" />
    <Resource Include="..\OTM.KioskShell\Assets\simplekioskos_side.png" Link="Assets\simplekioskos_side.png" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>Otm.Kiosk.Manager</RootNamespace>
    <ApplicationIcon>..\OTM.KioskShell\Assets\simplekioskos.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
