<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>Otm.Kiosk.Classroom</RootNamespace>
    <ApplicationIcon>..\OTM.KioskShell\Assets\simplekioskos.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OTM.Shared\OTM.Shared.csproj" />
  </ItemGroup>
</Project>
